[package]
name = "xic"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.3"
structopt = "0.2.14"
pretty = "0.5.2"
maplit = "1.0.1"
petgraph = "0.4.13"
rand = "0.6.5"

[build-dependencies]
lalrpop = "0.16.3"
