[package]
name = "xic"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.3"
structopt = "0.2.14"

[build-dependencies]
lalrpop = "0.16.3"
