#! /usr/bin/python3
import sys
import subprocess


def run_xth(path):
    script = path + "/xthScript"
    subprocess.run(["xth/xth", "-testpath", path, script])


def run_staff(project):
    path = "xth/tests/pa{}".format(project)
    run_xth(path)


def run_custom(project):
    path = "tests/pa{}".format(project)
    run_xth(path)


if __name__ == "__main__":
    try:
        suite = sys.argv[1]
        run_staff(suite)
        run_custom(suite)
    except Exception:
        print("Usage: ./xic-test 1")
